/:
  controller: Security
  action: installer

/setupapi:
  controller: Security
  action: setupapi

/site:
  controller: Security
  action: site

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/accueil:
  controller: Main
  action: index
  security: true

/comment:
  controller: CommentaireController
  action: commentaire
  security: true
  role: [ ADMIN ]

/addcomment:
  controller: CommentaireController
  action: addComment
  security: true
  role: [ ADMIN ]

/modifycomment:
  controller: CommentaireController
  action: modifyComment
  security: true
  role: [ ADMIN ]

/deletecomment:
  controller: CommentaireController
  action: deleteComment
  security: true
  role: [ ADMIN ]

/report:
  controller: CommentaireController
  action: report
  security: true

/article:
  controller: ArticleController
  action: article
  security: true
  role: [ ADMIN ]

/addarticle:
  controller: ArticleController
  action: addArticle
  security: true
  role: [ ADMIN ]

/modifyarticle:
  controller: ArticleController
  action: modifyArticle
  security: true
  role: [ ADMIN ]

/deletearticle:
  controller: ArticleController
  action: deleteArticle
  security: true
  role: [ ADMIN ]

/user:
  controller: UtilisateurController
  action: user
  security: true
  role: [ ADMIN ]

/adduser:
  controller: UtilisateurController
  action: addUser
  security: true
  role: [ ADMIN ]

/modifyuser:
  controller: UtilisateurController
  action: modifyUser
  security: true
  role: [ ADMIN, EDITOR ]

/deleteuser:
  controller: UtilisateurController
  action: deleteUser
  security: true
  role: [ ADMIN, EDITOR ]

/reset:
  controller: Main
  action: reset

/tempo:
  controller: Main
  action: tempo