/:
  controller: Main
  action: installer

/accueil:
  controller: Main
  action: index
  security: true

/report:
  controller: Main
  action: report
  security: true

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/article:
  controller: Security
  action: article
  security: true
  role: [ ADMIN ]

/addarticle:
  controller: Add
  action: addArticle
  security: true
  role: [ ADMIN ]

/adduser:
  controller: Add
  action: addUser
  security: true
  role: [ ADMIN ]

/modifyarticle:
  controller: Update
  action: modifyArticle
  security: true
  role: [ ADMIN ]

/deletearticle:
  controller: Delete
  action: deleteArticle
  security: true
  role: [ ADMIN ]

/user:
  controller: Security
  action: user
  security: true
  role: [ ADMIN ]