/:
  controller: Main
  action: installer

/accueil:
  controller: Main
  action: index
  security: true

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/page:
  controller: Security
  action: page
  security: true
  role: [ADMIN]

/addpage:
  controller: Add
  action: addPage
  security: true
  role: [ADMIN, EDITOR]

/adduser:
  controller: Add
  action: addUser

/modifypage:
  controller: Update
  action: modifyPage
  security: true
  role: [ADMIN, EDITOR]

/deletepage:
  controller: Delete
  action: deletePage
  security: true
  role: [ADMIN, EDITOR]

/user:
  controller: Security
  action: user


/admin:
  controller: Admin
  action: dashboard
  security: true
  role: [ADMIN, EDITOR]
