/:
  controller: Main
  action: index
  security: true

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/page:
  controller: Security
  action: page

/addpage:
  controller: Add
  action: addPage

/adduser:
  controller: Add
  action: addUser

/modifypage:
  controller: Update
  action: modifyPage

/deletepage:
  controller: Delete
  action: deletePage

/user:
  controller: Security
  action: user


/admin:
  controller: Admin
  action: dashboard
  security: true
  role: [ ADMIN,EDITOR ]
  