/:
  controller: Main
  action: installer

/accueil:
  controller: Main
  action: index
  security: true

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/register:
  controller: Security
  action: register

/article:
  controller: Security
  action: article
  security: true
  role: [ADMIN]

/addarticle:
  controller: Add
  action: addArticle
  security: true
  role: [ADMIN, EDITOR]

/adduser:
  controller: Add
  action: addUser

/modifyarticle:
  controller: Update
  action: modifyArticle
  security: true
  role: [ADMIN, EDITOR]

/deletearticle:
  controller: Delete
  action: deleteArticle
  security: true
  role: [ADMIN, EDITOR]

/user:
  controller: Security
  action: user


/admin:
  controller: Admin
  action: dashboard
  security: true
  role: [ADMIN, EDITOR]
